/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedNovoTrabalhoRouteImport } from './routes/_authenticated/novo-trabalho'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as PartilhaIdRouteImport } from './routes/partilha.$id'
import { Route as AuthenticatedAmostraIdRouteImport } from './routes/_authenticated/amostra.$id'
import { Route as AuthenticatedTrabalhoIdRouteImport } from './routes/_authenticated/trabalho.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNovoTrabalhoRoute =
  AuthenticatedNovoTrabalhoRouteImport.update({
    id: '/novo-trabalho',
    path: '/novo-trabalho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PartilhaIdRoute = PartilhaIdRouteImport.update({
  id: '/partilha/$id',
  path: '/partilha/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAmostraIdRoute = AuthenticatedAmostraIdRouteImport.update({
  id: '/amostra/$id',
  path: '/amostra/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrabalhoIdRoute = AuthenticatedTrabalhoIdRouteImport.update({
  id: '/trabalho/$id',
  path: '/trabalho/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/novo-trabalho': typeof AuthenticatedNovoTrabalhoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/partilha/$id': typeof PartilhaIdRoute
  '/amostra/$id': typeof AuthenticatedAmostraIdRoute
  '/trabalho/$id': typeof AuthenticatedTrabalhoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/novo-trabalho': typeof AuthenticatedNovoTrabalhoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/partilha/$id': typeof PartilhaIdRoute
  '/amostra/$id': typeof AuthenticatedAmostraIdRoute
  '/trabalho/$id': typeof AuthenticatedTrabalhoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/novo-trabalho': typeof AuthenticatedNovoTrabalhoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/partilha/$id': typeof PartilhaIdRoute
  '/_authenticated/amostra/$id': typeof AuthenticatedAmostraIdRoute
  '/_authenticated/trabalho/$id': typeof AuthenticatedTrabalhoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/novo-trabalho'
    | '/painel'
    | '/perfil'
    | '/planos'
    | '/partilha/$id'
    | '/amostra/$id'
    | '/trabalho/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/novo-trabalho'
    | '/painel'
    | '/perfil'
    | '/planos'
    | '/partilha/$id'
    | '/amostra/$id'
    | '/trabalho/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/novo-trabalho'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/planos'
    | '/partilha/$id'
    | '/_authenticated/amostra/$id'
    | '/_authenticated/trabalho/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PartilhaIdRoute: typeof PartilhaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/novo-trabalho': {
      id: '/_authenticated/novo-trabalho'
      path: '/novo-trabalho'
      fullPath: '/novo-trabalho'
      preLoaderRoute: typeof AuthenticatedNovoTrabalhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/partilha/$id': {
      id: '/partilha/$id'
      path: '/partilha/$id'
      fullPath: '/partilha/$id'
      preLoaderRoute: typeof PartilhaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/amostra/$id': {
      id: '/_authenticated/amostra/$id'
      path: '/amostra/$id'
      fullPath: '/amostra/$id'
      preLoaderRoute: typeof AuthenticatedAmostraIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trabalho/$id': {
      id: '/_authenticated/trabalho/$id'
      path: '/trabalho/$id'
      fullPath: '/trabalho/$id'
      preLoaderRoute: typeof AuthenticatedTrabalhoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNovoTrabalhoRoute: typeof AuthenticatedNovoTrabalhoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedAmostraIdRoute: typeof AuthenticatedAmostraIdRoute
  AuthenticatedTrabalhoIdRoute: typeof AuthenticatedTrabalhoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNovoTrabalhoRoute: AuthenticatedNovoTrabalhoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedAmostraIdRoute: AuthenticatedAmostraIdRoute,
  AuthenticatedTrabalhoIdRoute: AuthenticatedTrabalhoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PartilhaIdRoute: PartilhaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
